name: mobil1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  path: ^1.9.0
  sqflite: ^2.3.3
  path_provider_windows: ^2.2.1
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  
  # Firebase packages
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.2
  firebase_storage: ^12.3.2
  provider: ^6.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png
  android_12:
    image: assets/images/logo.png
    color: "#FFFFFF"
  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/avatars/





